"""
Publication-quality plotting functions for T2 relaxometry.

Every figure produced by the project is generated by a single callable
function in this module.  Notebooks call these functions directly.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from matplotlib.colors import ListedColormap, to_rgba
from matplotlib.patches import Patch

from utils import SEG_NAMES, SEG_COLOURS, mean_decay_curve, hard_seg

matplotlib.rcParams['figure.dpi'] = 100


# ===================================================================
# Shared colour maps and constants
# ===================================================================

def _seg_cmap():
    """Transparent background + semi-transparent tissue colours."""
    return ListedColormap([
        (0, 0, 0, 0.0),
        to_rgba(SEG_COLOURS[1], 0.45),
        to_rgba(SEG_COLOURS[2], 0.45),
        to_rgba(SEG_COLOURS[3], 0.45),
        to_rgba(SEG_COLOURS[4], 0.45),
        to_rgba(SEG_COLOURS[5], 0.45),
    ])


def _seg_legend():
    """Patch handles for the tissue-class legend."""
    return [Patch(facecolor=SEG_COLOURS[k], edgecolor='none',
                  label=SEG_NAMES[k]) for k in [1, 2, 3, 4, 5]]


TISSUE_COLOURS = {'CSF': '#ffc800', 'GM': '#16766b', 'WM': '#945ad6',
                  'Deep GM': '#09413a', 'Brainstem': '#c44536'}


# ===================================================================
# Task 1 figures
# ===================================================================

def plot_echo_gallery(datasets, n=3):
    """Show all echo times for the first n subjects, one row each."""
    for ds in datasets[:n]:
        sl = ds['reg'].shape[2] // 2
        n_te = len(ds['TE'])
        fig, axes = plt.subplots(1, n_te, figsize=(2 * n_te, 4))
        vmax = np.percentile(ds['reg'][..., 0], 99)
        for ax, k in zip(axes, range(n_te)):
            ax.imshow(ds['reg'][:, :, sl, k].T, cmap='gray',
                      origin='lower', vmin=0, vmax=vmax)
            ax.set_title(f'TE = {ds["TE"][k]:.1f} ms')
            ax.axis('off')
        plt.suptitle(f'Epicure{ds["id"]}, central axial slice')
        plt.tight_layout(); plt.show()


def plot_seg_overlay_slices(datasets, n=2, n_slices=5):
    """Hard segmentation overlay across representative axial slices."""
    from quality import representative_brain_slices
    labels = ['Bottom', 'Lower-mid', 'Middle', 'Upper-mid', 'Top']
    cmap = _seg_cmap()

    for ds in datasets[:n]:
        slices = representative_brain_slices(ds['mask'], n_slices)
        vmax = np.percentile(ds['reg'][..., 0], 99)
        seg_h = hard_seg(ds)

        fig, axes = plt.subplots(1, n_slices, figsize=(18, 4.5))
        for ax, sl, lab in zip(axes, slices, labels):
            img = ds['reg'][:, :, sl, 0].T
            seg2d = np.where(ds['mask'][:, :, sl].T, seg_h[:, :, sl].T, 0)
            ax.imshow(img, cmap='gray', origin='lower', vmin=0, vmax=vmax)
            ax.imshow(seg2d, cmap=cmap, origin='lower', vmin=0, vmax=5)
            ax.set_title(f'{lab} (slice {sl})', fontsize=10)
            ax.axis('off')
        axes[0].legend(handles=_seg_legend(), loc='lower left', fontsize=8)
        plt.suptitle(f'Epicure{ds["id"]}, hard segmentation overlay')
        plt.tight_layout(); plt.show()


def plot_soft_seg_channels(ds):
    """Six-panel display of soft segmentation probability channels."""
    sl = ds['reg'].shape[2] // 2
    img = ds['reg'][:, :, sl, 0].T
    vmax = np.percentile(ds['reg'][..., 0], 99)
    mask2d = ds['mask'][:, :, sl].T

    fig, axes = plt.subplots(2, 3, figsize=(13, 8))
    for k, ax in enumerate(axes.ravel()):
        seg2d = np.where(mask2d, ds['seg'][:, :, sl, k].T, 0.0)
        ax.imshow(img, cmap='gray', origin='lower', vmin=0, vmax=vmax)
        rgba = np.zeros(seg2d.shape + (4,), dtype=float)
        rgba[..., :3] = to_rgba(SEG_COLOURS.get(k, '#888'))[:3]
        if seg2d.max() > 0:
            rgba[..., 3] = 0.75 * (seg2d / seg2d.max())
        ax.imshow(rgba, origin='lower')
        ax.set_title(f'{k}: {SEG_NAMES[k]}'); ax.axis('off')
    plt.suptitle(f'Epicure{ds["id"]}, soft segmentation channels')
    plt.tight_layout(); plt.show()


def plot_tissue_decay_curves(datasets, n=3):
    """Segmentation overlay + semilog tissue-mean decay curves, n subjects."""
    cmap = _seg_cmap()
    fig, axes = plt.subplots(n, 2, figsize=(12, 3.5 * n))
    if n == 1:
        axes = axes.reshape(1, 2)

    for row, ds in enumerate(datasets[:n]):
        sl = ds['reg'].shape[2] // 2
        seg_h = hard_seg(ds)
        img = ds['reg'][:, :, sl, 0].T
        vmax = np.percentile(ds['reg'][..., 0], 99)
        seg_show = np.where(ds['mask'][:, :, sl].T, seg_h[:, :, sl].T, 0)

        axes[row, 0].imshow(img, cmap='gray', origin='lower', vmin=0, vmax=vmax)
        axes[row, 0].imshow(seg_show, cmap=cmap, origin='lower', vmin=0, vmax=5)
        axes[row, 0].set_title(f'Epicure{ds["id"]}'); axes[row, 0].axis('off')

        for k in [1, 2, 3, 4, 5]:
            c = mean_decay_curve(ds, k)
            axes[row, 1].semilogy(ds['TE'], c, 'o-', color=SEG_COLOURS[k],
                                  lw=1.4, ms=4, label=SEG_NAMES[k])
        axes[row, 1].set_xlabel('TE (ms)')
        axes[row, 1].set_ylabel('mean signal (log)')
        axes[row, 1].set_title(f'Epicure{ds["id"]} — mean decay by tissue')
        axes[row, 1].grid(False)

    axes[0, 0].legend(handles=_seg_legend(), loc='lower left', fontsize=8)
    axes[0, 1].legend(fontsize=8)
    plt.tight_layout(); plt.show()


def plot_voxel_heterogeneity(ds, seg_idx=3, n_voxels=200, seed=0):
    """Semilog overlay of n random WM voxel decay curves."""
    from utils import region_signals
    wm = region_signals(ds, seg_idx=seg_idx)
    rng = np.random.default_rng(seed)
    idx = rng.choice(len(wm), size=min(n_voxels, len(wm)), replace=False)

    fig, ax = plt.subplots(figsize=(8, 4.2))
    for i, vi in enumerate(idx):
        curve_n = wm[vi] / max(wm[vi, 0], 1e-6)
        ax.semilogy(ds['TE'], curve_n, alpha=0.65, lw=1.1,
                    color=plt.cm.viridis(i / len(idx)))
    ax.set(xlabel='TE (ms)', ylabel='normalised signal (log)',
           title=f'Epicure{ds["id"]} — {len(idx)} random WM voxel decays')
    ax.grid(False); plt.tight_layout(); plt.show()


def plot_monotonicity_map(ds, viol_map):
    """Side-by-side: TE1 anatomy and monotonicity violation map."""
    sl = viol_map.shape[2] // 2
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    axes[0].imshow(ds['reg'][:, :, sl, 0].T, cmap='gray', origin='lower')
    axes[0].set_title(f'Epicure{ds["id"]} — TE1'); axes[0].axis('off')

    img = viol_map[:, :, sl].copy()
    img[~ds['mask'][:, :, sl]] = np.nan
    cm = plt.get_cmap('Reds').copy(); cm.set_bad('white')
    im = axes[1].imshow(img.T, cmap=cm, origin='lower', vmin=0, vmax=0.4)
    plt.colorbar(im, ax=axes[1], label='violation fraction')
    axes[1].set_title('monotonicity violations'); axes[1].axis('off')
    plt.tight_layout(); plt.show()


def plot_snr_curves(preterm):
    """Per-subject SNR vs echo time, coloured by EP/FT."""
    from quality import estimate_sigma_bg
    fig, ax = plt.subplots(figsize=(8, 4.2))
    for ds in preterm:
        sigma = estimate_sigma_bg(ds['reg'], ds['mask'])
        mean_sig = np.array([ds['reg'][ds['mask'], k].mean()
                             for k in range(len(ds['TE']))])
        snr = mean_sig / sigma
        colour = 'firebrick' if ds['EP'] else 'steelblue'
        ax.plot(ds['TE'], snr, '-', lw=0.6, alpha=0.35, color=colour)
    ax.axhline(3, color='k', ls='--', lw=1, label='SNR = 3')
    ax.set(xlabel='TE (ms)', ylabel='mean in-brain SNR',
           title=f'Preterm cohort — per-echo mean SNR (n = {len(preterm)})\n'
                 'red = EP, blue = FT')
    ax.grid(True, alpha=0.3); ax.legend(fontsize=9)
    plt.tight_layout(); plt.show()


def plot_logfit_residuals(ds, seg_list=(1, 2, 3)):
    """Semilog decay + log-linear fit + residuals for CSF/GM/WM."""
    from quality import fit_logline_and_residuals
    fig, axes = plt.subplots(2, len(seg_list), figsize=(12, 6), sharex=True)

    for j, seg_idx in enumerate(seg_list):
        c = mean_decay_curve(ds, seg_idx)
        xfit, yfit, res = fit_logline_and_residuals(c, ds['TE'])
        axes[0, j].semilogy(ds['TE'], c, 'bo-', lw=1.5, ms=3, label='data')
        axes[0, j].semilogy(xfit, yfit, 'r--', lw=1.2, label='log-linear fit')
        axes[0, j].set_title(SEG_NAMES[seg_idx]); axes[0, j].grid(False)
        axes[1, j].plot(xfit, res, 'bo-', lw=1.2, ms=3)
        axes[1, j].axhline(0, color='r', ls='--', lw=1.0)
        axes[1, j].set_xlabel('TE (ms)'); axes[1, j].grid(False)
    axes[0, 0].set_ylabel('signal (log)')
    axes[1, 0].set_ylabel('log-fit residual')
    axes[0, 0].legend(fontsize=8)
    plt.suptitle(f'Epicure{ds["id"]} — mono-exponentiality test')
    plt.tight_layout(); plt.show()


def plot_qa_deep_dive(group_title, group_df, id_to_ds):
    """Violation maps + tissue decay curves for a set of flagged subjects."""
    from quality import check_monotonicity
    n = len(group_df)
    fig, axes = plt.subplots(n, 2, figsize=(9, 3.2 * n))
    if n == 1:
        axes = axes.reshape(1, 2)

    for r, (_, row) in enumerate(group_df.iterrows()):
        ds = id_to_ds[row['id']]
        _, _, viol_map = check_monotonicity(ds['reg'], ds['mask'])
        sl = ds['reg'].shape[2] // 2

        img = viol_map[:, :, sl].copy()
        img[~ds['mask'][:, :, sl]] = np.nan
        cm = plt.get_cmap('Reds').copy(); cm.set_bad('white')
        im = axes[r, 0].imshow(img.T, cmap=cm, origin='lower', vmin=0, vmax=0.4)
        plt.colorbar(im, ax=axes[r, 0], fraction=0.045, label='violation frac')
        axes[r, 0].set_title(f'Epicure{row["id"]}'); axes[r, 0].axis('off')

        for k, name, c in [(1, 'CSF', '#ffc800'), (2, 'GM', '#16766b'),
                            (3, 'WM', '#945ad6')]:
            curve = mean_decay_curve(ds, k)
            axes[r, 1].semilogy(ds['TE'], curve, 'o-', color=c, lw=1.4,
                                label=name)
        axes[r, 1].set_xlabel('TE (ms)'); axes[r, 1].legend(fontsize=8)
        axes[r, 1].grid(False)

    plt.suptitle(group_title, y=1.00)
    plt.tight_layout(); plt.show()


# ===================================================================
# Task 2 figures
# ===================================================================

def plot_two_point_maps(ds, pairs=None):
    """2-point T2 maps for several echo pairs on one subject."""
    from analysis import two_point_T2_map
    TE = ds['TE']
    if pairs is None:
        pairs = [(0, 2), (0, 6), (0, 9)]
    sl = ds['reg'].shape[2] // 2

    fig, axes = plt.subplots(1, len(pairs), figsize=(13, 4.2))
    for ax, (ia, ib) in zip(axes, pairs):
        T2_map = two_point_T2_map(ds['reg'], TE, ds['mask'], idx_a=ia, idx_b=ib)
        img = T2_map[:, :, sl].copy()
        img[~ds['mask'][:, :, sl]] = np.nan
        cm = plt.get_cmap('hot').copy(); cm.set_bad('white')
        im = ax.imshow(img.T, origin='lower', cmap=cm, vmin=0, vmax=500)
        ax.set_title(f'TE pair: {TE[ia]:.0f} → {TE[ib]:.0f} ms'); ax.axis('off')
        plt.colorbar(im, ax=ax, fraction=0.045, label='T2 (ms)')
    plt.suptitle(f'Epicure{ds["id"]} — 2-point T2 maps')
    plt.tight_layout(); plt.show()


def plot_tissue_fits_3panel(ds, tissues=None):
    """Linear, log, and residual panels for OLS/WLS/NLLS on tissue-mean curves."""
    from models import mono_exp, fit_log_linear, fit_nlls
    from models import fit_wls
    if tissues is None:
        tissues = [(1, 'CSF'), (2, 'GM'), (3, 'WM')]

    TE = np.asarray(ds['TE'], float)
    fig, axes = plt.subplots(len(tissues), 3, figsize=(14, 4 * len(tissues)))

    for i, (seg_idx, lab) in enumerate(tissues):
        curve = mean_decay_curve(ds, seg_idx)
        S0_ols, T2_ols = fit_log_linear(TE, curve)
        S0_wls, T2_wls = fit_wls(TE, curve)
        S0_nll, T2_nll = fit_nlls(TE, curve)
        TE_fine = np.linspace(TE.min(), TE.max(), 200)

        # Linear
        ax = axes[i, 0]
        ax.plot(TE, curve, 'ko', ms=6, label='data')
        ax.plot(TE_fine, mono_exp(TE_fine, S0_ols, T2_ols), 'b--',
                label=f'OLS T2={T2_ols:.1f}')
        ax.plot(TE_fine, mono_exp(TE_fine, S0_wls, T2_wls), 'g:',
                label=f'WLS T2={T2_wls:.1f}')
        ax.plot(TE_fine, mono_exp(TE_fine, S0_nll, T2_nll), 'r-',
                label=f'NLLS T2={T2_nll:.1f}')
        ax.set(xlabel='TE (ms)', ylabel='signal', title=f'{lab}, linear')
        ax.legend(fontsize=8)

        # Log
        axes[i, 1].semilogy(TE, curve, 'ko', ms=6)
        axes[i, 1].semilogy(TE_fine, mono_exp(TE_fine, S0_ols, T2_ols), 'b--')
        axes[i, 1].semilogy(TE_fine, mono_exp(TE_fine, S0_wls, T2_wls), 'g:')
        axes[i, 1].semilogy(TE_fine, mono_exp(TE_fine, S0_nll, T2_nll), 'r-')
        axes[i, 1].set(xlabel='TE (ms)', ylabel='signal (log)',
                       title=f'{lab}, log scale')

        # Residuals
        axes[i, 2].axhline(0, color='k', lw=1)
        for S0, T2, fmt, lbl in [(S0_ols, T2_ols, 'bo--', 'OLS'),
                                   (S0_wls, T2_wls, 'go:', 'WLS'),
                                   (S0_nll, T2_nll, 'ro-', 'NLLS')]:
            axes[i, 2].plot(TE, (curve - mono_exp(TE, S0, T2)) / S0, fmt,
                            label=f'{lbl} res/$S_0$')
        axes[i, 2].set(xlabel='TE (ms)', ylabel='normalised residual',
                       title=f'{lab}, residuals')
        axes[i, 2].legend(fontsize=8)

    fig.suptitle(f'Epicure{ds["id"]}, tissue-mean fits', y=1.02)
    plt.tight_layout(); plt.show()


def plot_cohort_residuals(preterm, tissues=None):
    """Cohort NLLS residuals by tissue, EP vs FT colour-coded."""
    from models import mono_exp, fit_nlls
    if tissues is None:
        tissues = {1: 'CSF', 2: 'GM', 3: 'WM'}

    fig, axes = plt.subplots(1, len(tissues), figsize=(13, 4), sharey=True)
    for ax, (seg_idx, label) in zip(axes, tissues.items()):
        for ds in preterm:
            curve = mean_decay_curve(ds, seg_idx)
            S0, T2 = fit_nlls(ds['TE'], curve)
            if not np.isfinite(T2):
                continue
            residual = curve - mono_exp(ds['TE'], S0, T2)
            colour = 'firebrick' if ds['EP'] else 'steelblue'
            ax.plot(ds['TE'], residual / S0, 'o-', lw=0.9, alpha=0.6,
                    color=colour)
        ax.axhline(0, color='k', lw=0.8)
        ax.set(xlabel='TE (ms)', title=f'{label} — NLLS residuals')
        ax.grid(False)
    axes[0].set_ylabel('residual / $S_0$')
    plt.suptitle('Cohort NLLS residuals (red = EP, blue = FT)')
    plt.tight_layout(); plt.show()


def plot_t2_map(T2_map, ds):
    """Single-slice T2 map with hot colourmap."""
    sl = T2_map.shape[2] // 2
    img = T2_map[:, :, sl].copy()
    img[~ds['mask'][:, :, sl]] = np.nan
    fig, ax = plt.subplots(figsize=(5.5, 5))
    cm = plt.get_cmap('hot').copy(); cm.set_bad('white')
    im = ax.imshow(img.T, origin='lower', cmap=cm, vmin=0, vmax=300)
    plt.colorbar(im, ax=ax, label='T2 (ms)')
    ax.set_title(f'Epicure{ds["id"]} — log-linear T2 map'); ax.axis('off')
    plt.tight_layout(); plt.show()


# ===================================================================
# Task 3 figures
# ===================================================================

def plot_biexp_decomposition(ds, S0, v, T2s=20.0, T2l=80.0):
    """Linear + log panels showing the bi-exp short/long decomposition."""
    from models import bi_exp_fixed
    TE = np.asarray(ds['TE'], float)
    wm = mean_decay_curve(ds, 3)
    TE_fine = np.linspace(TE.min(), TE.max(), 300)

    fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))
    sig_tot = bi_exp_fixed(TE_fine, S0, v, T2s, T2l)
    sig_sh = S0 * v * np.exp(-TE_fine / T2s)
    sig_lo = S0 * (1 - v) * np.exp(-TE_fine / T2l)

    axes[0].plot(TE, wm, 'ko', ms=6, label='WM data', zorder=5)
    axes[0].plot(TE_fine, sig_tot, 'r-', lw=2, label='total fit')
    axes[0].plot(TE_fine, sig_sh, 'b--', lw=1.5, label=f'short ({T2s:.0f} ms)')
    axes[0].plot(TE_fine, sig_lo, 'g--', lw=1.5, label=f'long ({T2l:.0f} ms)')
    axes[0].set(xlabel='TE (ms)', ylabel='signal', title='Linear')
    axes[0].legend(fontsize=8)

    axes[1].semilogy(TE, wm, 'ko', ms=6, zorder=5)
    axes[1].semilogy(TE_fine, sig_tot, 'r-', lw=2)
    axes[1].set(xlabel='TE (ms)', ylabel='signal (log)', title='Log')

    fig.suptitle(f'Epicure{ds["id"]} WM, v = {v:.3f}, S0 = {S0:.1f}', y=1.03)
    plt.tight_layout(); plt.show()


def plot_ci_intervals(df_ci, tissues=('CSF', 'GM', 'WM')):
    """Interval plot of v with 95% bootstrap CIs, coloured by EP/FT."""
    fig, axes = plt.subplots(1, len(tissues), figsize=(13, 4.5), sharey=False)
    for ax, tissue in zip(axes, tissues):
        sub = df_ci[df_ci['tissue'] == tissue].sort_values('v').reset_index(drop=True)
        y = np.arange(len(sub))
        colours = ['firebrick' if ep else 'steelblue' for ep in sub['EP']]
        for yi, row, c in zip(y, sub.itertuples(index=False), colours):
            ax.plot([row.CI_low, row.CI_high], [yi, yi], color=c, lw=1.2, alpha=0.7)
        ax.scatter(sub['v'], y, c=colours, s=18, alpha=0.9, zorder=3)
        ax.set_xlabel('v'); ax.set_title(tissue); ax.set_yticks([]); ax.grid(False)
    axes[0].set_ylabel('subjects ranked by v')
    plt.suptitle('Fixed-T2 v with 95% bootstrap CIs (red = EP, blue = FT)')
    plt.tight_layout(); plt.show()


def plot_ci_boxplots(df_ci, tissues=('CSF', 'GM', 'WM')):
    """Boxplots of v by tissue and EP/FT group."""
    fig, axes = plt.subplots(1, len(tissues), figsize=(10, 4), sharey=True)
    for ax, tissue in zip(axes, tissues):
        sub = df_ci[df_ci['tissue'] == tissue]
        vals_ft = sub.loc[sub['EP'] == False, 'v'].dropna().values
        vals_ep = sub.loc[sub['EP'] == True, 'v'].dropna().values
        ax.boxplot([vals_ft, vals_ep], labels=['FT', 'EP'], widths=0.45,
                   patch_artist=True, showfliers=True,
                   boxprops=dict(facecolor='white', edgecolor='blue', lw=1.2),
                   medianprops=dict(color='red', lw=1.2),
                   flierprops=dict(marker='+', markeredgecolor='red', ms=6))
        ax.set_title(tissue); ax.grid(False)
    axes[0].set_ylabel('v')
    plt.suptitle('Bootstrap v estimates by tissue and group', y=1.02)
    plt.tight_layout(); plt.show()


# ===================================================================
# Task 4 figures
# ===================================================================

def plot_aicc_scatter(df_cmp, tissues=('WM', 'GM', 'CSF')):
    """Per-subject dAICc scatter, negative = 2-comp preferred."""
    fig, axes = plt.subplots(1, len(tissues), figsize=(13, 4), sharey=True)
    for ax, tissue in zip(axes, tissues):
        sub = df_cmp[df_cmp['tissue'] == tissue]
        colours = ['firebrick' if ep else 'steelblue' for ep in sub['EP']]
        ax.scatter(range(len(sub)), sub['dAICc'], c=colours, s=14, alpha=0.7)
        ax.axhline(0, color='k', lw=1)
        ax.axhline(-2, color='g', ls='--', lw=0.8, label='2-comp preferred')
        ax.axhline(+2, color='r', ls='--', lw=0.8, label='1-comp preferred')
        ax.set(xlabel='subject', title=tissue)
    axes[0].set_ylabel('dAICc (2-comp − 1-comp)')
    axes[0].legend(fontsize=8)
    plt.suptitle('AICc per subject (negative = 2-comp wins)')
    plt.tight_layout(); plt.show()


def plot_mcmc_vs_bootstrap(post, v_hat_m, ci_m, v_hat_b, ci_b, ds):
    """MCMC trace + posterior histogram vs bootstrap 95% CI."""
    lo_m, hi_m = ci_m
    lo_b, hi_b = ci_b
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))

    axes[0].plot(post, lw=0.5, color='steelblue')
    axes[0].axhline(v_hat_m, color='red', lw=1, label=f'median = {v_hat_m:.3f}')
    axes[0].set(xlabel='iteration (post burn-in)', ylabel='v', title='MCMC trace')
    axes[0].legend(fontsize=8)

    axes[1].hist(post, bins=40, density=True, alpha=0.5, color='steelblue',
                 label='MCMC posterior')
    axes[1].axvspan(lo_b, hi_b, alpha=0.2, color='firebrick',
                    label=f'Boot 95% CI [{lo_b:.3f}, {hi_b:.3f}]')
    axes[1].axvline(v_hat_b, color='firebrick', lw=1.5, ls='--',
                    label=f'Boot v = {v_hat_b:.3f}')
    axes[1].set(xlabel='v', ylabel='density', title='Posterior vs bootstrap')
    axes[1].legend(fontsize=8)

    plt.suptitle(f'Parameter precision — Epicure{ds["id"]} WM')
    plt.tight_layout(); plt.show()


# ===================================================================
# Task 5 figures
# ===================================================================

def plot_nnls_plain_vs_reg(ds, a_plain, a_reg, mu_star, T2_grid):
    """Data fit and T2 spectrum: plain vs regularised NNLS."""
    from models import make_kernel
    TE = ds['TE']
    wm = mean_decay_curve(ds, 3)
    K = make_kernel(TE, T2_grid)

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    axes[0].semilogy(TE, wm, 'ko', ms=6, label='data', zorder=5)
    axes[0].semilogy(TE, K @ a_plain, 'r-', lw=1.6, label='plain NNLS')
    axes[0].semilogy(TE, K @ a_reg, 'b--', lw=1.6,
                     label=f'regularised (μ={mu_star:.2g})')
    axes[0].set(xlabel='TE (ms)', ylabel='signal (log)',
                title=f'WM fit, Epicure{ds["id"]}')
    axes[0].legend(fontsize=8)

    axes[1].semilogx(T2_grid, a_plain, 'r-', lw=1.3, alpha=0.7, label='plain')
    axes[1].semilogx(T2_grid, a_reg, 'b-', lw=1.8, label='regularised')
    axes[1].axvspan(10, 40, color='grey', alpha=0.15, label='myelin (10–40 ms)')
    axes[1].set(xlabel='T2 (ms)', ylabel='amplitude', title='T2 spectrum')
    axes[1].legend(fontsize=8)
    plt.tight_layout(); plt.show()


def plot_cohort_spectra(spectra, T2_grid, tissues=None):
    """Per-tissue NNLS spectra across the cohort."""
    if tissues is None:
        tissues = {'CSF': 'royalblue', 'GM': 'forestgreen', 'WM': 'firebrick'}
    fig, axes = plt.subplots(1, len(tissues), figsize=(14, 4),
                             sharex=True, sharey=True)
    for ax, (t, col) in zip(axes, tissues.items()):
        mat = np.asarray(spectra[t])
        for row in mat:
            ax.semilogx(T2_grid, row, color='grey', alpha=0.15, lw=0.6)
        ax.semilogx(T2_grid, mat.mean(axis=0), color=col, lw=2, label='mean')
        ax.axvspan(10, 40, color='gold', alpha=0.15, label='myelin')
        ax.axvspan(50, 150, color='lightgreen', alpha=0.15, label='IE water')
        ax.axvspan(1000, 2000, color='lightblue', alpha=0.15, label='CSF')
        ax.set(xlabel='T2 (ms)', title=f'{t} (n = {mat.shape[0]})')
    axes[0].set_ylabel('amplitude'); axes[0].legend(fontsize=7)
    plt.suptitle('Preterm cohort NNLS T2 spectra')
    plt.tight_layout(); plt.show()


def plot_mwf_2v3(df_mwf):
    """Scatter: 2-comp v vs 3-comp v1 (Dingwall), EP/FT colours."""
    fig, ax = plt.subplots(figsize=(6, 5))
    for flag, col in [(True, 'firebrick'), (False, 'steelblue')]:
        sub = df_mwf[df_mwf['EP'] == flag]
        ax.scatter(sub['v_2comp'], sub['MWF_3comp'], s=22, alpha=0.7,
                   color=col, label='EP' if flag else 'FT')
    lim = [0, df_mwf[['v_2comp', 'MWF_3comp']].max().max() * 1.1]
    ax.plot(lim, lim, 'k--', lw=1, alpha=0.5, label='y = x')
    ax.set(xlabel='2-comp v', ylabel='3-comp v1 (Dingwall)',
           title='WM MWF: 2-comp vs 3-comp', xlim=lim, ylim=lim)
    ax.legend(fontsize=9); ax.grid(alpha=0.3)
    plt.tight_layout(); plt.show()


# ===================================================================
# Task 6 figures
# ===================================================================

def plot_mwf_maps(maps, labels, ds, sl):
    """Side-by-side MWF maps for different fitting strategies."""
    msl = ds['mask'][:, :, sl]
    fig, axes = plt.subplots(1, len(maps), figsize=(5 * len(maps), 4.5))
    for ax, vmap, title in zip(axes, maps, labels):
        cm = plt.get_cmap('magma').copy(); cm.set_bad('white')
        img = vmap.copy(); img[~msl] = np.nan
        im = ax.imshow(img.T, origin='lower', cmap=cm, vmin=0, vmax=0.5)
        ax.set_title(title); ax.axis('off')
        plt.colorbar(im, ax=ax, fraction=0.045, label='v (MWF)')
    plt.suptitle(f'Epicure{ds["id"]} — MWF maps, slice {sl}')
    plt.tight_layout(); plt.show()


def plot_mwf_histograms(maps, labels, wm_mask, mu_wm, ds, sl):
    """Histogram overlay of voxel-level v distributions in WM."""
    colours = ['firebrick', 'steelblue', 'forestgreen']
    fig, ax = plt.subplots(figsize=(8, 4))
    for vmap, name, c in zip(maps, labels, colours):
        vals = vmap[wm_mask]; vals = vals[np.isfinite(vals)]
        ax.hist(vals, bins=40, range=(0, 0.8), histtype='step', lw=1.6,
                color=c, label=name)
    ax.axvline(mu_wm, color='black', ls='--', lw=1.0,
               label=f'cohort WM μ = {mu_wm:.2f}')
    ax.set(xlabel='voxel v (MWF)', ylabel='count',
           title=f'Epicure{ds["id"]} WM voxel MWF, slice {sl}')
    ax.legend(fontsize=9); ax.grid(alpha=0.3)
    plt.tight_layout(); plt.show()


# ===================================================================
# Task 7 figures
# ===================================================================

def plot_group_boxplots(df):
    """Whole-WM T2 and MWF boxplots with p-value annotation."""
    from analysis import ttest_summary, sig_marker
    fig, axes = plt.subplots(1, 2, figsize=(8, 4), dpi=150)

    for ax, col, ylab, title in [
        (axes[0], 'T2_WM', 'WM T2 (ms)', 'Whole-WM T2'),
        (axes[1], 'v_MWF', 'WM MWF (v)', 'Whole-WM MWF'),
    ]:
        ep = pd.to_numeric(df.loc[df['EP'] == True, col], errors='coerce').dropna()
        ft = pd.to_numeric(df.loc[df['EP'] == False, col], errors='coerce').dropna()
        ax.boxplot([ep, ft], positions=[1, 2], widths=0.5, patch_artist=True,
                   showfliers=False,
                   boxprops=dict(facecolor='white', edgecolor='blue', lw=1),
                   medianprops=dict(color='red', lw=1),
                   whiskerprops=dict(color='gray', ls='--', lw=1),
                   capprops=dict(color='gray', lw=1))

        res = ttest_summary(ep.values, ft.values)
        mark = sig_marker(res['p'])
        ymin, ymax = ax.get_ylim()
        y_bar = ymax + 0.04 * (ymax - ymin)
        ax.plot([1, 2], [y_bar, y_bar], 'k-', lw=1)
        ax.text(1.5, y_bar + 0.01 * (ymax - ymin),
                f'p = {res["p"]:.3f}{" " + mark if mark else " (ns)"}',
                ha='center', va='bottom', fontsize=9)
        ax.set_ylim(ymin, y_bar + 0.10 * (ymax - ymin))
        ax.set_title(title); ax.set_ylabel(ylab)
        ax.set_xticks([1, 2])
        ax.set_xticklabels([f'preterm (n={len(ep)})',
                            f'term (n={len(ft)})'], fontsize=9)
    plt.suptitle('Whole-WM comparison (* p<0.05, ns = not significant)')
    plt.tight_layout(); plt.show()


def plot_sex_stratified(df_merged):
    """Two-panel boxplot: EP vs FT within female / male."""
    from analysis import ttest_summary, sig_marker
    fig, axes = plt.subplots(1, 2, figsize=(9, 4), dpi=150)
    positions = [1, 2, 4, 5]

    for ax, col, title, ylab in [
        (axes[0], 'T2_WM', 'White matter T2', 'T2 (ms)'),
        (axes[1], 'v_MWF', 'White matter MWF', 'MWF (v)'),
    ]:
        data = []
        for sex_code in [0, 1]:
            for ep_flag in [True, False]:
                vals = pd.to_numeric(
                    df_merged[(df_merged['EP'] == ep_flag)
                              & (df_merged['male'] == sex_code)][col],
                    errors='coerce').dropna()
                data.append(vals)

        ax.boxplot(data, positions=positions, widths=0.65, patch_artist=True,
                   showfliers=False,
                   boxprops=dict(facecolor='white', edgecolor='blue', lw=1),
                   medianprops=dict(color='red', lw=1),
                   whiskerprops=dict(color='gray', ls='--'),
                   capprops=dict(color='gray'))

        # Annotate pairs
        for pos_pair, (ep_vals, ft_vals) in [([1, 2], [data[0], data[1]]),
                                              ([4, 5], [data[2], data[3]])]:
            res = ttest_summary(ep_vals.values, ft_vals.values)
            if res is None:
                continue
            ymin, ymax = ax.get_ylim()
            y_bar = ymax + 0.04 * (ymax - ymin)
            ax.plot(pos_pair, [y_bar, y_bar], 'k-', lw=1)
            mark = sig_marker(res['p'])
            ax.text(np.mean(pos_pair), y_bar,
                    f'p={res["p"]:.3f}{" " + mark if mark else " (ns)"}',
                    ha='center', va='bottom', fontsize=8)

        ax.set_title(title); ax.set_ylabel(ylab)
        ax.set_xticks(positions)
        ax.set_xticklabels(['PT', 'FT', 'PT', 'FT'], fontsize=9)
        ymin, ymax = ax.get_ylim()
        ax.text(1.5, ymin + 0.02 * (ymax - ymin), 'female', ha='center', fontsize=9)
        ax.text(4.5, ymin + 0.02 * (ymax - ymin), 'male', ha='center', fontsize=9)

    plt.suptitle('WM parameters by group × sex')
    plt.tight_layout(); plt.show()


def plot_iq_scatter(merged):
    """WM T2 and MWF vs FSIQ with per-group Spearman annotations."""
    from scipy import stats as sp_stats
    from analysis import sig_marker
    fig, axes = plt.subplots(1, 2, figsize=(11, 4), dpi=150)

    for ax, col, ylab in [(axes[0], 'T2_WM', 'WM T2 (ms)'),
                          (axes[1], 'v_MWF', 'WM MWF (v)')]:
        for flag, c, lab in [(True, 'firebrick', 'EP'),
                             (False, 'steelblue', 'FT')]:
            sub = merged[merged['EP'] == flag]
            ax.scatter(sub['y19ps_fsiq_comp'], sub[col], s=22, alpha=0.7,
                       color=c, label=lab)

            sub_clean = sub.dropna(subset=[col, 'y19ps_fsiq_comp'])
            if len(sub_clean) >= 5:
                rho, p_rho = sp_stats.spearmanr(sub_clean['y19ps_fsiq_comp'],
                                                 sub_clean[col])
                mark = sig_marker(p_rho)
                y_pos = 0.97 if flag else 0.88
                ax.text(0.03, y_pos,
                        f'{lab}: ρ = {rho:+.3f}, p = {p_rho:.3f}'
                        f'{" " + mark if mark else " (ns)"}',
                        transform=ax.transAxes, ha='left', va='top',
                        fontsize=9, color=c,
                        bbox=dict(facecolor='white', edgecolor='none', alpha=0.85))

        ax.set(xlabel='FSIQ', ylabel=ylab)
        ax.legend(fontsize=8); ax.grid(alpha=0.3)
    plt.suptitle('WM parameters vs cognitive outcome (FSIQ)')
    plt.tight_layout(); plt.show()


def plot_regional_grid(df_reg, stats_df, wm_regions):
    """2×4 grid: T2 (top) and MWF (bottom) boxplots per region with p-values."""
    from analysis import ttest_summary, sig_marker
    bonf_thr = 0.05 / len(stats_df)

    fig, axes = plt.subplots(2, len(wm_regions), figsize=(14, 7),
                             sharey='row', dpi=150)

    for row_i, (metric, ylab) in enumerate([('T2', 'WM T2 (ms)'),
                                             ('v', 'WM MWF (v)')]):
        for col_i, rname in enumerate(wm_regions.values()):
            ax = axes[row_i, col_i]
            sub = df_reg[df_reg['region'] == rname]
            ep = pd.to_numeric(sub.loc[sub['EP'] == True, metric],
                               errors='coerce').dropna()
            ft = pd.to_numeric(sub.loc[sub['EP'] == False, metric],
                               errors='coerce').dropna()

            ax.boxplot([ep, ft], positions=[1, 2], widths=0.5,
                       patch_artist=True, showfliers=False,
                       boxprops=dict(facecolor='white', edgecolor='blue', lw=1),
                       medianprops=dict(color='red', lw=1),
                       whiskerprops=dict(color='gray', ls='--'),
                       capprops=dict(color='gray'))

            res = ttest_summary(ep.values, ft.values)
            if res:
                mark = sig_marker(res['p'], bonf_thr)
                ymin, ymax = ax.get_ylim()
                y_bar = ymax + 0.04 * (ymax - ymin)
                ax.plot([1, 2], [y_bar, y_bar], 'k-', lw=1)
                ax.text(1.5, y_bar,
                        f'p={res["p"]:.3f}{" " + mark if mark else " (ns)"}',
                        ha='center', va='bottom', fontsize=8)

            ax.set_title(rname, fontsize=10)
            ax.set_xticks([1, 2])
            ax.set_xticklabels([f'PT (n={len(ep)})', f'FT (n={len(ft)})'],
                               fontsize=8)
            if col_i == 0:
                ax.set_ylabel(ylab)

    plt.suptitle('Regional WM analysis\n'
                 f'* uncorrected p<0.05  ** Bonferroni p<0.05 (α={bonf_thr:.4f})')
    plt.tight_layout(); plt.show()


def plot_ga_scatter(df):
    """WM T2 and MWF vs gestational age."""
    fig, axes = plt.subplots(1, 2, figsize=(11, 4), dpi=150)
    for ax, col, ylab in [(axes[0], 'T2_WM', 'WM T2 (ms)'),
                          (axes[1], 'v_MWF', 'WM MWF (v)')]:
        for flag, colour, lab in [(True, 'firebrick', 'EP'),
                                   (False, 'steelblue', 'FT')]:
            sub = df[df['EP'] == flag]
            ax.scatter(sub['gawks'], sub[col], s=22, alpha=0.7,
                       color=colour, label=lab)
        ax.set(xlabel='gestational age (weeks)', ylabel=ylab)
        ax.legend(fontsize=8); ax.grid(alpha=0.3)
    plt.suptitle('Whole-WM parameters vs gestational age')
    plt.tight_layout(); plt.show()
